# Generated by Django 4.2.9 on 2024-02-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='owner_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Fixed', 'Fixed'), ('Pending Approval', 'Pending Approval'), ('Approved for Inspection', 'Approved for Inspection'), ('Rejected for Inspection', 'Rejected for Inspection'), ('Inspection Done', 'Inspection Done'), ('Quotation Created', 'Quotation Created')], default='Pending Approval', max_length=60),
        ),
    ]
