# Generated by Django 4.2.9 on 2024-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_maintenanceticket_owner_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='maintenance_status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved for Inspection', 'Approved for Inspection'), ('Rejected for Inspection', 'Rejected for Inspection'), ('Quotation Created', 'Quotation Created')], default='Pending Maintenance', max_length=60),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved for Inspection', 'Approved for Inspection'), ('Rejected for Inspection', 'Rejected for Inspection'), ('Quotation Created', 'Quotation Created')], default='Pending Approval for Inspection', max_length=80),
        ),
    ]
