# Generated by Django 4.2.9 on 2024-04-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_maintenanceticket_maintenance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque_date', models.DateField()),
                ('cheque_owner', models.CharField(max_length=70)),
                ('bank_name', models.CharField(max_length=50)),
                ('paid_to', models.CharField(max_length=70)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='website.record')),
            ],
        ),
    ]
