# Generated by Django 4.2.9 on 2024-04-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_documents',
            field=models.FileField(blank=True, null=True, upload_to='property_documents/'),
        ),
    ]
