# Generated by Django 4.2.9 on 2024-04-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_property_property_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_documents',
        ),
    ]
