# Generated by Django 5.0 on 2024-04-23 08:38

import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='property',
            name='property_doc_info',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_document',
            field=models.FileField(default=1, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
            preserve_default=False,
        ),
    ]
