# Generated by Django 5.0 on 2024-04-23 10:45

import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_delete_document_property_property_doc_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_doc_info',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_document',
        ),
        migrations.AddField(
            model_name='property',
            name='property_doc_info_1',
            field=models.CharField(blank=True, choices=[('Title Deed', 'Title Deed'), ('Passport or Emirates ID', 'Emirates ID'), ('POA Document', 'POA Document')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_doc_info_2',
            field=models.CharField(blank=True, choices=[('Title Deed', 'Title Deed'), ('Passport or Emirates ID', 'Emirates ID'), ('POA Document', 'POA Document')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_doc_info_3',
            field=models.CharField(blank=True, choices=[('Title Deed', 'Title Deed'), ('Passport or Emirates ID', 'Emirates ID'), ('POA Document', 'POA Document')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_document_1',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
        ),
        migrations.AddField(
            model_name='property',
            name='property_document_2',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
        ),
        migrations.AddField(
            model_name='property',
            name='property_document_3',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
        ),
    ]
