# Generated by Django 5.0 on 2024-04-23 11:13

import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_property_property_doc_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tenant_doc_info_1',
            field=models.CharField(blank=True, choices=[('Ejari', 'Ejari'), ('Passport', 'Passport'), ('Tenancy Contract', 'Tenancy Contract'), ('Emirates ID', 'Emirates ID'), ('Visa', 'Visa'), ('Cheque/Cash Receipt', 'Cheque/Cash Receipt')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_doc_info_2',
            field=models.CharField(blank=True, choices=[('Ejari', 'Ejari'), ('Passport', 'Passport'), ('Tenancy Contract', 'Tenancy Contract'), ('Emirates ID', 'Emirates ID'), ('Visa', 'Visa'), ('Cheque/Cash Receipt', 'Cheque/Cash Receipt')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_doc_info_3',
            field=models.CharField(blank=True, choices=[('Ejari', 'Ejari'), ('Passport', 'Passport'), ('Tenancy Contract', 'Tenancy Contract'), ('Emirates ID', 'Emirates ID'), ('Visa', 'Visa'), ('Cheque/Cash Receipt', 'Cheque/Cash Receipt')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_doc_info_4',
            field=models.CharField(blank=True, choices=[('Ejari', 'Ejari'), ('Passport', 'Passport'), ('Tenancy Contract', 'Tenancy Contract'), ('Emirates ID', 'Emirates ID'), ('Visa', 'Visa'), ('Cheque/Cash Receipt', 'Cheque/Cash Receipt')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_doc_info_5',
            field=models.CharField(blank=True, choices=[('Ejari', 'Ejari'), ('Passport', 'Passport'), ('Tenancy Contract', 'Tenancy Contract'), ('Emirates ID', 'Emirates ID'), ('Visa', 'Visa'), ('Cheque/Cash Receipt', 'Cheque/Cash Receipt')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_doc_info_6',
            field=models.CharField(blank=True, choices=[('Ejari', 'Ejari'), ('Passport', 'Passport'), ('Tenancy Contract', 'Tenancy Contract'), ('Emirates ID', 'Emirates ID'), ('Visa', 'Visa'), ('Cheque/Cash Receipt', 'Cheque/Cash Receipt')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_document_1',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_document_2',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_document_3',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_document_4',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_document_5',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
        ),
        migrations.AddField(
            model_name='record',
            name='tenant_document_6',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg']), website.models.validate_file_mimetype]),
        ),
    ]
